const serviceModule = {
  adminLogin: {/*后台登录接口*/
    url: 'admin/validUser',
    method: 'post'
  },
  adminLoadUser:{/*后台加载用户信息*/
    url:'admin/loadUser',
    method:'get'
  },
  adminMenu:{/*后台左侧菜单*/
    url:'admin/menu',
    method:'get'
  },
  adminShopInfoShow:{/*网站基本信息展示*/
    url:'admin/shopInfo',
    method:'get'
  },
  adminSaveShopInfo:{/*网站基本信息设置*/
    url:'admin/shopInfo',
    method:'post'
  },
  adminShopBannerList:{/*首页轮播图列表*/
    url:'admin/shopBannerList',
    method:'get'
  },
  adminShopBannerAdd:{/*新增首页轮播图以及保存修改后的轮播图信息*/
    url:'admin/shopBannerSave',
    method:'post'
  },
  adminShopBannerEdit:{/*加载需要编辑的首页轮播图的相关信息*/
    url:'admin/shopBannerEdit',
    method:'get'
  },
  adminShopBannerDel:{/*删除首页轮播图*/
    url:'admin/shopBannerDel',
    method:'post'
  },
  adminShopBannerImgUpload:{/*上传首页轮播图图片*/
    url:'admin/bannerFileUpload',
    method:'post'
  },
  adminUserTypeList:{/*会员类型列表*/
    url:'admin/userTypeList',
    method:'get'
  },
  adminUserTypeEdit:{/*会员类型编辑*/
    url:'admin/userTypeEdit',
    method:'get'
  },
  adminUserTypeSave:{/*新增会员类型或保存修改后的会员类型信息*/
    url:'admin/userTypeSave',
    method:'post'
  },
  adminUserTypeDel:{/*删除用户类型*/
    url:'admin/userTypeDel',
    method:'post'
  },
  adminGoodsPlateList:{/*商品板块列表*/
    url:'admin/goodsPlateList',
    method:'get'
  },
  adminGoodsPlateEdit:{/*商品板块编辑*/
    url:'admin/goodsPlateEdit',
    method:'get'
  },
  adminGoodsPlateSave:{/*编辑后的商品板块保存*/
    url:'admin/goodsPlateSave',
    method:'post'
  },
  adminGoodsPlateDel:{/*商品板块信息删除*/
    url:'admin/goodsPlateDel',
    method:'post'
  },
  adminGoodsTypeList:{/*商品类别列表*/
    url:'admin/goodsTypeList',
    method:'get'
  },
  adminGoodsTypeAdd:{/*新增商品类别*/
    url:'admin/goodsTypeSave',
    method:'post'
  },
  adminGoodsTypeEdit:{/*商品类别编辑*/
    url:'admin/goodsTypeEdit',
    method:'get'
  },
  adminGoodsTypeDel:{/*删除商品类别*/
    url:'admin/goodsTypeDel',
    method:'post'
  },
  adminNewsList:{/*新闻列表*/
    url:'admin/shopNewsList',
    method:'get'
  },
  adminNewsPreview:{/*新闻预览*/
    url:'admin/shopNewsView',
    method:'get'
  },
  adminNewsAdd:{/*新增新闻公告*/
    url:'admin/shopNewsSave',
    method:'post'
  },
  adminUploadImg:{/*上传新闻的图片*/
    url:'admin/newsFileUpload',
    method:'post'
  }
}
const ApiSetting = { ...serviceModule }

export default ApiSetting
